[package]
name = "querier"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "13"
async-trait = "0.1.53"
backoff = { path = "../backoff" }
client_util = { path = "../client_util" }
data_types = { path = "../data_types" }
datafusion = { path = "../datafusion" }
datafusion_util = { path = "../datafusion_util" }
futures = "0.3"
generated_types = { path = "../generated_types" }
influxdb_iox_client = { path = "../influxdb_iox_client" }
iox_catalog = { path = "../iox_catalog" }
metric = { path = "../metric" }
object_store = { path = "../object_store" }
observability_deps = { path = "../observability_deps" }
parking_lot = "0.12"
parquet_file = { path = "../parquet_file" }
pin-project = "1.0"
predicate = { path = "../predicate" }
query = { path = "../query" }
rand = "0.8.3"
service_common = { path = "../service_common" }
schema = { path = "../schema" }
snafu = "0.7"
thiserror = "1.0"
iox_time = { path = "../iox_time" }
tokio = { version = "1.18", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.7.1" }
tonic = { version = "0.7" }
trace = { path = "../trace" }
uuid = { version = "0.8", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
arrow_util = { path = "../arrow_util" }
assert_matches = "1.5"
criterion = "0.3"
iox_tests = { path = "../iox_tests" }
mutable_batch_lp = { path = "../mutable_batch_lp" }
proptest = { version = "1", default_features = false, features = ["std"] }
test_helpers = { path = "../test_helpers" }

[[bench]]
name = "addressable_heap"
harness = false
