[package]
name = "grpc-router"
version = "0.1.0"
authors = ["Marko Mikulicic <mkm@influxdata.com>"]
edition = "2021"

[dependencies]
cache_loader_async = {version  = "0.2.0", features = ["ttl-cache"] }
futures = "0.3"
observability_deps = { path = "../observability_deps" }
paste = "1.0.7"
thiserror = "1.0.31"
tokio = { version = "1.18", features = ["macros", "parking_lot", "rt-multi-thread"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = "0.7"

[dev-dependencies]
grpc-router-test-gen = { path = "../grpc-router-test-gen" }
